name: wooapp
description: WooCommerce customer mobile application.
publish_to: 'none'
version: 0.9.1+1

environment:
  sdk: ">=2.18.1 <3.7.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  flutter_bloc: ^8.1.1
  fluttertoast: ^8.0.3
  flutter_rating_bar: ^4.0.0
  # ToDo replace share lib
  share: ^2.0.4
  page_view_indicators: ^2.0.0
  font_awesome_flutter: ^10.3.0
  intl: ^0.17.0
  provider: ^6.0.5
  dio: ^5.0.0
  html: ^0.15.0
  shared_preferences: ^2.0.5
  infinite_scroll_pagination: ^3.0.1+1
  cached_network_image: ^3.0.0
  shimmer_animation: ^2.0.0
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  validators: ^3.0.0
  lottie: ^2.1.0
  image: ^3.3.0
  invert_colors: ^0.0.3-null-safety.0
  photo_view: ^0.14.0
  easy_localization: ^3.0.1
  google_maps_flutter: ^2.0.6
  fluster: ^1.2.0
  package_info_plus: ^3.0.3
  url_launcher: ^6.1.9
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
     - .env
     - assets/animations/
     - assets/images/
     - assets/translations/
