import 'package:flutter/material.dart';

/// Contains WooApp material color palette configuration.
///
/// Generated by: https://m3.material.io/theme-builder#/custom
/// Input primary color: #005d99
class WooAppTheme {
  static const Color colorCommonBackground = Color(0xFFfdfcff);
  static const Color colorCommonText = Color(0xFF1a1c1e);
  static const Color colorCommonText2 = Color(0xda001d35);

  static const Color colorCommonSectionBackground = Color(0xccd6e4f7);
  static const Color colorCommonSectionForeground = Color(0xFF0f1d2a);

  static const Color colorShimmerBackground = Color(0x59d6e4f7);
  static const Color colorShimmerForeground = Color(0xFF241432);

  static const Color colorToolbarBackground = Color(0xFF0062a0);
  static const Color colorToolbarForeground = Color(0xFFd0e4ff);

  static const Color colorPrimaryBackground = Color(0xFF0062a0);
  static const Color colorPrimaryForeground = Color(0xFFFFFFFF);

  static const Color colorSecondaryBackground = Color(0xFFdfe3eb);
  static const Color colorSecondaryForeground = Color(0xFF526070);

  static const Color colorDangerActionBackground = Color(0xFFffb4ab);
  static const Color colorDangerActionForeground = Color(0xFF690005);

  static const Color colorFeaturedSearchBackground = Color(0xba2982b9);
  static const Color colorFeaturedSearchBorder = Color(0x40d0e4ff);//Color(0x808BC0EA);

  static const Color colorBottomBarIconNonActive = Color(0x996a5779);
  static const Color colorBottomBarIconActive = Color(0xff241432);
  // static const Color colorBottomBarBackground = Color(0xFFfdfcff);
  static const Color colorBottomBarBackground = Color(0xffededf1);

  static const Color colorRatingActive = Color(0xFFDC810B);
  static const Color colorRatingNonActive = Color(0x99526070);
  static const Color colorRatingText = Color(0xFF241432);

  static const Color colorCardProductBackground = Color(0xffedf4ff);
  static const Color colorCardProductText = Color(0xFF001d35);

  static const Color colorProductStatusBgInStock = Color(0xFFFFFFFF);
  static const Color colorProductStatusTextInStock = Colors.lightGreen;

  static const Color colorProductStatusBgOutOfStock = Color(0xFFFFFFFF);
  static const Color colorProductStatusTextOutOfStock = Colors.redAccent;

  static const Color colorProductStatusBgBackOrder = Color(0xFF5A4D0D);
  static const Color colorProductStatusTextBackOrder = Colors.amberAccent;

  static const Color colorProductStatusBgDefault = Color(0xFFFFF3F3);
  static const Color colorProductStatusTextDefault = Colors.redAccent;

  static const Color colorOrderStatusBgBlue = Color(0xFF9ccaff);
  static const Color colorOrderStatusTextBlue = Color(0xFF003256);
  static const Color colorOrderStatusBgGray2 = Color(0xFF3b4857);
  static const Color colorOrderStatusTextGray2 = Color(0xFFd6e4f7);
  static const Color colorOrderStatusBgGray = Color(0xFFdfe3eb);
  static const Color colorOrderStatusTextGray = Color(0xFF42474e);
  static const Color colorOrderStatusBgPink = Color(0xFFf1daff);
  static const Color colorOrderStatusTextPink = Color(0xFF241432);
  static const Color colorOrderStatusBgRed = Color(0xFF93000a);
  static const Color colorOrderStatusTextRed = Color(0xFFffdad6);
  static const Color colorOrderStatusBgYellow = Color(0xfff8dda7);
  static const Color colorOrderStatusTextYellow = Color(0xff9c6e1a);
  static const Color colorOrderStatusBgGreen = Color(0xffc0eaaf);
  static const Color colorOrderStatusTextGreen = Color(0xff42650c);

  static const Color colorCardOrderBackground = colorCardProductBackground;
  static const Color colorCardOrderForeground = colorCardProductText;

  static const Color colorCreateOrderHeaderText = colorCommonSectionForeground;
  static const Color colorCardCreateOrderBackground = colorCommonSectionBackground;
  static const Color colorCardCreateOrderText = Color(0xFF565D88);

  static const Color colorPrice = Color(0xFF1a1c1e);
  static const Color colorPriceSale = Color(0xFFba1a1a);

  static const Color colorAuthBackground = Color(0xff0062a0);
  static const Color colorAuthHeaderText = Color(0xFFdfe3eb);
  static const Color colorAuthActionText = Color(0xFFf1daff);
  static const Color colorAuthActionBackground = Color(0xFF1a1c1e);
  static const Color colorAuthFieldText = Color(0xFFd0e4ff);
  static const Color colorAuthNotValidFieldText = Color(0xFFba1a1a);
}
